name: lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore uTelemetry.sln

      - name: Verify formatting
        run: dotnet format uTelemetry.sln --verify-no-changes --no-restore --severity warn
